In [1]:
import os

os.chdir('/workspaces/fuzzy-expert')

In [2]:
from fuzzy_expert.operators import extremely
extremely([0, 0.25, 0.5, 0.75, 1])

array([0.      , 0.015625, 0.125   , 0.421875, 1.      ])

In [3]:
from fuzzy_expert.operators import intensify
intensify([0, 0.25, 0.5, 0.75, 1])

array([0.    , 0.0625, 0.25  , 0.875 , 1.    ])

In [4]:
from fuzzy_expert.operators import more_or_less
more_or_less([0, 0.25, 0.5, 0.75, 1])

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
from fuzzy_expert.operators import norm
norm([0, 0.25, 0.5])

array([0. , 0.5, 1. ])

In [6]:
from fuzzy_expert.operators import not_
not_([0, 0.25, 0.5, 0.75, 1])

array([1.  , 0.75, 0.5 , 0.25, 0.  ])

In [7]:
from fuzzy_expert.operators import plus
plus([0, 0.25, 0.5, 0.75, 1])

array([0.        , 0.1767767 , 0.42044821, 0.69795364, 1.        ])

In [8]:
from fuzzy_expert.operators import somewhat
somewhat([0, 0.25, 0.5, 0.75, 1])

array([0.        , 0.62996052, 0.79370053, 0.9085603 , 1.        ])

In [9]:
from fuzzy_expert.operators import very
very([0, 0.25, 0.5, 0.75, 1])

array([0.    , 0.0625, 0.25  , 0.5625, 1.    ])

In [10]:
from fuzzy_expert.operators import slightly
slightly([0, 0.25, 0.5, 0.75, 1])

array([0.        , 0.16326531, 0.99696182, 1.        , 0.        ])

In [11]:
from fuzzy_expert.operators import bounded_sum
x = [0, 0.25, 0.5, 0.75, 1]
bounded_sum([x, x, x])

array([0.  , 0.75, 1.  , 1.  , 1.  ])

In [12]:
from fuzzy_expert.operators import drastic_prod
x = [0, 0.25, 0.5, 0.75, 1]
y = [1, 0.75, 0.5, 0.25, 0]
drastic_prod([x, y])

array([0., 0., 0., 0., 1.])

In [13]:
from fuzzy_expert.operators import drastic_sum
x = [0.1, 0.25, 0.5, 0.75, 0.3]
y = [0, 0.75, 0.5, 0.25, 0]
drastic_sum([x, y])

array([0.1, 1. , 1. , 1. , 0.3])

In [14]:
from fuzzy_expert.operators import product
x = [0, 0.25, 0.5, 0.75, 1]
product([x, x, x])

array([0.      , 0.015625, 0.125   , 0.421875, 1.      ])

In [15]:
from fuzzy_expert.operators import maximum
x = [0.1, 0.25, 0.5, 0.75, 0.3]
y = [0, 0.75, 0.5, 0.25, 0]
maximum([x, y])

array([0.1 , 0.75, 0.5 , 0.75, 0.3 ])

In [16]:
from fuzzy_expert.operators import minimum
x = [0.1, 0.25, 0.5, 0.75, 0.3]
y = [0, 0.75, 0.5, 0.25, 0]
minimum([x, y])

array([0.  , 0.25, 0.5 , 0.25, 0.  ])

In [17]:
from fuzzy_expert.operators import apply_modifiers
x = [0.0, 0.25, 0.5, 0.75, 1]
apply_modifiers(x, ('not', 'very'))


array([1.    , 0.9375, 0.75  , 0.4375, 0.    ])

In [18]:
from fuzzy_expert.operators import prob_or
x = [0.1, 0.25, 0.5, 0.75, 0.3]
y = [0, 0.75, 0.5, 0.25, 0]
prob_or([x, y])

array([0.1   , 0.8125, 0.75  , 0.8125, 0.3   ])

In [19]:
>>> from fuzzy_expert.operators import bounded_prod
>>> x = [0.1, 0.25, 0.5, 0.75, 1]
>>> bounded_prod([x, x])

array([0. , 0. , 0. , 0.5, 1. ])

In [20]:
    >>> from fuzzy_expert.operators import bounded_diff
    >>> x = [0, 0.25, 0.5, 0.75, 1]
    >>> y = [0, 0.25, 0.5, 0.6, 0.7]
    >>> bounded_diff([x, y])

array([0.  , 0.  , 0.  , 0.15, 0.3 ])